services:
  nginx-website:
    image: docker.io/library/nginx:1.26.3-alpine
    container_name: nginx-website
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.nginx-website-http.entrypoints=web
      - traefik.http.routers.nginx-website-http.rule=Host(`dragonwolfsp.com`)
      - traefik.http.routers.nginx-website-https.entrypoints=websecure
      - traefik.http.routers.nginx-website-https.rule=Host(`dragonwolfsp.com`)
      - traefik.http.routers.nginx-website-https.tls=true
      - traefik.http.routers.nginx-website-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    depends_on:
      - php
    restart: unless-stopped
  php:
    image: php:fpm
    container_name: php-fpm-website
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html
    networks:
      - backend
  gitsync:
    environment:
      - LOG_ROTATE_CYCLE=5
      - GITSYNC_URL=https://github.com/dragonwolfsp/dragonwolfsp.com
      - GITSYNC_BRANCH=deploy
      - GITSYNC_CHECKOUT=true
    volumes:
      - ./data:/data
      - ./sync-logs:/log
    image: ustcmirror/gitsync:latest
    container_name: gitsync-website
    restart: unless-stopped
networks:
  frontend:
    external: true
  backend:
    external: true
